#!/usr/bin/env python3
"""
Build XAUUSD_Adaptive_Bot_V5_main.py — the single self-contained file that
cTrader actually runs.

cTrader embeds and executes only the MAIN Python file of a cBot, so the whole
V5 system has to live in one file: the shared detectors from adaptive_bot/,
every module of adaptive_bot_v5/, and the cBot class itself.  This script
concatenates them in dependency order, strips the local/relative imports and
the duplicated standard-library imports, and writes one header that imports
everything once.

Run from the ctrader_bot directory:
    python3 build_v5_single_file.py
"""

import os
import re
import sys

BOT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(BOT_DIR, "XAUUSD_Adaptive_Bot_V5_main.py")

MODULES = [
    ("SHARED - DATA MODEL", "adaptive_bot/core/models.py"),
    ("SHARED - DETECTOR CONFIG (base class for the shared detectors)",
     "adaptive_bot/core/config.py"),
    ("SHARED - MATH HELPERS", "adaptive_bot/core/helpers.py"),
    ("SHARED - MARKET STRUCTURE", "adaptive_bot/strategy/market_structure.py"),
    ("SHARED - LIQUIDITY", "adaptive_bot/strategy/liquidity.py"),
    ("SHARED - SUPPLY/DEMAND + ORDER BLOCKS",
     "adaptive_bot/strategy/supply_demand.py"),
    ("SHARED - FAIR VALUE GAPS", "adaptive_bot/strategy/fair_value_gap.py"),
    ("SHARED - MARKET REGIME", "adaptive_bot/strategy/regime.py"),
    ("SHARED - SESSIONS", "adaptive_bot/filters/session_filter.py"),
    ("SHARED - NEWS PROTECTION (schedule-based only)",
     "adaptive_bot/filters/news_filter.py"),
    ("SHARED - SPREAD FILTER", "adaptive_bot/filters/spread_filter.py"),
    ("SHARED - POSITION SIZING", "adaptive_bot/risk/position_sizing.py"),
    ("SHARED - DAILY/WEEKLY LOSS GUARD (base)",
     "adaptive_bot/risk/daily_loss_guard.py"),
    ("V5 - CONFIGURATION + VALIDATOR", "adaptive_bot_v5/config_v5.py"),
    ("V5 - PER-TIMEFRAME FEATURES", "adaptive_bot_v5/features_v5.py"),
    ("V5 - MULTI-TIMEFRAME MARKET STATE",
     "adaptive_bot_v5/market_state_v5.py"),
    ("V5 - CONFLUENCE ENGINE (group-capped)", "adaptive_bot_v5/confluence.py"),
    ("V5 - STRUCTURAL STOPS AND TARGETS", "adaptive_bot_v5/trade_plan.py"),
    ("V5 - TRADE MANAGEMENT STATE MACHINE (shared by shadow and real)",
     "adaptive_bot_v5/management.py"),
    ("V5 - SETUP FAMILIES (mandatory MTF sequences)",
     "adaptive_bot_v5/setups_v5.py"),
    ("V5 - SHADOW PORTFOLIOS", "adaptive_bot_v5/shadow_v5.py"),
    ("V5 - REAL POSITION RECORD + BROKER LEVELS",
     "adaptive_bot_v5/execution_v5.py"),
    ("V5 - STATISTICAL LEARNING", "adaptive_bot_v5/learning_v5.py"),
    ("V5 - RESEARCH CLOCK (active trading days)",
     "adaptive_bot_v5/research_clock.py"),
    ("V5 - GUARDS, RISK ENGINE, ORDER PREFLIGHT", "adaptive_bot_v5/risk_v5.py"),
    ("V5 - PERSISTENCE", "adaptive_bot_v5/persistence_v5.py"),
    ("V5 - REPORTING", "adaptive_bot_v5/reporting_v5.py"),
]

STDLIB_PREFIXES = (
    "import csv", "import json", "import math", "import os", "import random",
    "import re", "import sys", "import uuid",
    "from dataclasses import", "from datetime import", "from enum import",
    "from typing import",
)

HEADER = '''\
"""
============================================================================
XAUUSD_Adaptive_Bot_V5 -- multi-timeframe CONFLUENCE research bot
                          (GOLD only, DEMO only, single self-contained file)
============================================================================

SINGLE-FILE BUILD.  cTrader embeds and executes only the main Python file of
a cBot, so this file inlines the entire V5 system: the shared detectors
(market structure, liquidity, supply/demand, order blocks, fair-value gaps,
regime, sessions, news, spread, sizing, guards) and every V5 module -- the
multi-timeframe market state, the group-capped confluence engine, structural
stops and targets, the ONE trade-management state machine that shadow and
real trades share, the six setup families, the shadow portfolios, statistical
learning, the active-trading-day research clock, persistence and reporting.

NO folders, NO package imports, NO third-party packages, NO network access,
NO self-modifying code.  Generated by build_v5_single_file.py -- edit the
modular source, then rebuild.

WHAT CHANGED FROM V4
  V4 entered on standalone signals (a liquidity sweep plus a reclaim was
  enough).  V5 requires a MANDATORY multi-timeframe sequence before a setup
  exists, then scores the remaining evidence with a correlation-aware
  confluence engine and still demands a minimum score.  Six genuinely
  different setup families are researched, and the ranking reports the family
  as well as the variant.  Shadow trades now run the same management as real
  trades, exit labels are truthful, R and MFE share one denominator, bid/ask
  handling is symmetric, and stale or gapped fills are refused.

ABSOLUTE RAILS (stricter than V4; there is no live switch anywhere)
  * DEMO-only ("LIVE ACCOUNT BLOCKED" + stop) and GOLD-only allowlist
  * one real position; broker-side SL+TP on every order; stops never widen
  * 0.25% max risk/trade, graduated slowly upward from 0.10% with evidence
  * 4 real trades/day maximum
  * 1.7% combined daily loss lock; 5% weekly drawdown lock
  * cooldown after 3 consecutive losses; volume always rounded DOWN
  * minimum volatility-based stop distance (no unrealistically tight stops)
  * no martingale, no grid, no averaging down, no recovery sizing
  * restarting never resets the guards or the research clock, and the clock
    counts ACTIVE TRADING DAYS, so weekends cost no research days

RESEARCH OUTPUT (in <home>/Documents/XAUUSD_Adaptive_Bot_V5/)
  research_state.json, shadow_trades.csv, real_trades.csv,
  rejected_setups.csv, strategy_rankings.csv, family_rankings.csv,
  daily_summary.csv, equity_history.csv, learning_log.csv,
  parameter_updates.csv, management_events.csv, suspect_trades.csv,
  stop_watch.csv, heartbeat.csv, daily_report_*.txt,
  final_report.txt / final_report.json

NEWS PROTECTION is schedule-based and MANUAL.  There is no live news feed in
this bot and none is claimed: maintain fomc_events / cpi_events in V5Config.

The final result is labelled "PROVISIONAL WINNER -- NOT AUTOMATICALLY READY
FOR LIVE TRADING."  No profitability is claimed.  This is a demo research
instrument, not a trading recommendation.
"""

import clr

clr.AddReference("cAlgo.API")

from cAlgo.API import *
from robot_wrapper import *

import csv
import json
import math
import os
import random
import uuid
from dataclasses import dataclass, field
from datetime import date, datetime, timedelta, timezone
from enum import Enum
from typing import Callable, Dict, List, Optional, Sequence, Tuple
'''


def strip_module(src):
    """Remove __future__, local imports and duplicated stdlib imports."""
    out = []
    lines = src.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()
        skip = False
        if stripped.startswith("from __future__"):
            skip = True
        elif stripped.startswith(("from .", "from ..", "from adaptive_bot",
                                  "import adaptive_bot")):
            skip = True
        elif any(stripped.startswith(p) for p in STDLIB_PREFIXES):
            skip = True
        if skip:
            # swallow a parenthesised continuation
            if "(" in stripped and ")" not in stripped:
                while i + 1 < len(lines) and ")" not in lines[i]:
                    i += 1
            i += 1
            continue
        out.append(line)
        i += 1
    text = "\n".join(out)
    text = re.sub(r"\n{4,}", "\n\n\n", text)
    return text.strip("\n")


def main():
    parts = [HEADER]
    for title, rel in MODULES:
        path = os.path.join(BOT_DIR, rel)
        with open(path, encoding="utf-8") as fh:
            src = fh.read()
        bar = "#" * 77
        parts.append(f"\n\n{bar}\n# {title}\n{bar}\n\n{strip_module(src)}")

    with open(os.path.join(BOT_DIR, "XAUUSD_Adaptive_Bot_V5.py"),
              encoding="utf-8") as fh:
        main_src = fh.read()
    marker = 'BOT_LABEL = "XAUUSD_Adaptive_Bot_V5"'
    tail = main_src[main_src.index(marker):]
    bar = "#" * 77
    parts.append(f"\n\n{bar}\n# THE cBOT — the only section that talks to the "
                 f"cTrader API\n{bar}\n\n{tail.strip()}\n")

    merged = "\n".join(parts)

    # the single file must be genuinely self-contained
    problems = []
    for forbidden in ("from adaptive_bot", "import adaptive_bot", "__file__",
                      "sys.path", "from .", "import requests", "urllib",
                      "http"):
        if forbidden in merged:
            problems.append(f"single file still references {forbidden!r}")
    if "class XAUUSD_Adaptive_Bot_V5(object):" not in merged:
        problems.append("cBot class missing from the merged file")
    for needed in ("DECISION_TF", "def on_start", "def on_tick", "def on_stop",
                   "LIVE ACCOUNT BLOCKED", "PROVISIONAL WINNER"):
        if needed not in merged:
            problems.append(f"merged file is missing {needed!r}")
    if problems:
        for p in problems:
            print(f"BUILD ERROR: {p}")
        return 1

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(merged)
    print(f"wrote {OUT}: {len(merged.splitlines())} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
